// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyEngineMessage.proto

#include "MyEngineMessage.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace LoginMessage {
PROTOBUF_CONSTEXPR Name_Repeat_Check::Name_Repeat_Check(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Name_Repeat_CheckDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Name_Repeat_CheckDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Name_Repeat_CheckDefaultTypeInternal() {}
  union {
    Name_Repeat_Check _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Name_Repeat_CheckDefaultTypeInternal _Name_Repeat_Check_default_instance_;
PROTOBUF_CONSTEXPR Name_Repeat_Repost::Name_Repeat_Repost(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.state_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Name_Repeat_RepostDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Name_Repeat_RepostDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Name_Repeat_RepostDefaultTypeInternal() {}
  union {
    Name_Repeat_Repost _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Name_Repeat_RepostDefaultTypeInternal _Name_Repeat_Repost_default_instance_;
PROTOBUF_CONSTEXPR MainMessage::MainMessage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_.content_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct MainMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MainMessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MainMessageDefaultTypeInternal() {}
  union {
    MainMessage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MainMessageDefaultTypeInternal _MainMessage_default_instance_;
}  // namespace LoginMessage
static ::_pb::Metadata file_level_metadata_MyEngineMessage_2eproto[3];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_MyEngineMessage_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_MyEngineMessage_2eproto = nullptr;

const uint32_t TableStruct_MyEngineMessage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::LoginMessage::Name_Repeat_Check, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::LoginMessage::Name_Repeat_Check, _impl_.name_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::LoginMessage::Name_Repeat_Repost, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::LoginMessage::Name_Repeat_Repost, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::LoginMessage::Name_Repeat_Repost, _impl_.state_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::LoginMessage::MainMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::LoginMessage::MainMessage, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::LoginMessage::MainMessage, _impl_.type_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::LoginMessage::MainMessage, _impl_.content_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::LoginMessage::Name_Repeat_Check)},
  { 7, -1, -1, sizeof(::LoginMessage::Name_Repeat_Repost)},
  { 15, -1, -1, sizeof(::LoginMessage::MainMessage)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::LoginMessage::_Name_Repeat_Check_default_instance_._instance,
  &::LoginMessage::_Name_Repeat_Repost_default_instance_._instance,
  &::LoginMessage::_MainMessage_default_instance_._instance,
};

const char descriptor_table_protodef_MyEngineMessage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025MyEngineMessage.proto\022\014LoginMessage\"!\n"
  "\021Name_Repeat_Check\022\014\n\004name\030\001 \001(\014\"1\n\022Name"
  "_Repeat_Repost\022\014\n\004name\030\001 \001(\014\022\r\n\005state\030\002 "
  "\001(\010\"\254\001\n\013MainMessage\022\'\n\004type\030\001 \001(\0162\031.Logi"
  "nMessage.MessageType\0223\n\010content1\030\002 \001(\0132\037"
  ".LoginMessage.Name_Repeat_CheckH\000\0224\n\010con"
  "tent2\030\003 \001(\0132 .LoginMessage.Name_Repeat_R"
  "epostH\000B\t\n\007content*<\n\013MessageType\022\025\n\021NAM"
  "E_REPEAT_CHECK\020\000\022\026\n\022NAME_REPEAT_REPOST\020\001"
  "b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_MyEngineMessage_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_MyEngineMessage_2eproto = {
    false, false, 368, descriptor_table_protodef_MyEngineMessage_2eproto,
    "MyEngineMessage.proto",
    &descriptor_table_MyEngineMessage_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_MyEngineMessage_2eproto::offsets,
    file_level_metadata_MyEngineMessage_2eproto, file_level_enum_descriptors_MyEngineMessage_2eproto,
    file_level_service_descriptors_MyEngineMessage_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_MyEngineMessage_2eproto_getter() {
  return &descriptor_table_MyEngineMessage_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_MyEngineMessage_2eproto(&descriptor_table_MyEngineMessage_2eproto);
namespace LoginMessage {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_MyEngineMessage_2eproto);
  return file_level_enum_descriptors_MyEngineMessage_2eproto[0];
}
bool MessageType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class Name_Repeat_Check::_Internal {
 public:
};

Name_Repeat_Check::Name_Repeat_Check(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:LoginMessage.Name_Repeat_Check)
}
Name_Repeat_Check::Name_Repeat_Check(const Name_Repeat_Check& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Name_Repeat_Check* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:LoginMessage.Name_Repeat_Check)
}

inline void Name_Repeat_Check::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Name_Repeat_Check::~Name_Repeat_Check() {
  // @@protoc_insertion_point(destructor:LoginMessage.Name_Repeat_Check)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Name_Repeat_Check::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
}

void Name_Repeat_Check::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Name_Repeat_Check::Clear() {
// @@protoc_insertion_point(message_clear_start:LoginMessage.Name_Repeat_Check)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Name_Repeat_Check::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Name_Repeat_Check::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:LoginMessage.Name_Repeat_Check)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes name = 1;
  if (!this->_internal_name().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LoginMessage.Name_Repeat_Check)
  return target;
}

size_t Name_Repeat_Check::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LoginMessage.Name_Repeat_Check)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Name_Repeat_Check::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Name_Repeat_Check::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Name_Repeat_Check::GetClassData() const { return &_class_data_; }


void Name_Repeat_Check::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Name_Repeat_Check*>(&to_msg);
  auto& from = static_cast<const Name_Repeat_Check&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:LoginMessage.Name_Repeat_Check)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Name_Repeat_Check::CopyFrom(const Name_Repeat_Check& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LoginMessage.Name_Repeat_Check)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Name_Repeat_Check::IsInitialized() const {
  return true;
}

void Name_Repeat_Check::InternalSwap(Name_Repeat_Check* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Name_Repeat_Check::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MyEngineMessage_2eproto_getter, &descriptor_table_MyEngineMessage_2eproto_once,
      file_level_metadata_MyEngineMessage_2eproto[0]);
}

// ===================================================================

class Name_Repeat_Repost::_Internal {
 public:
};

Name_Repeat_Repost::Name_Repeat_Repost(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:LoginMessage.Name_Repeat_Repost)
}
Name_Repeat_Repost::Name_Repeat_Repost(const Name_Repeat_Repost& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Name_Repeat_Repost* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.state_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.state_ = from._impl_.state_;
  // @@protoc_insertion_point(copy_constructor:LoginMessage.Name_Repeat_Repost)
}

inline void Name_Repeat_Repost::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.state_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Name_Repeat_Repost::~Name_Repeat_Repost() {
  // @@protoc_insertion_point(destructor:LoginMessage.Name_Repeat_Repost)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Name_Repeat_Repost::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
}

void Name_Repeat_Repost::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Name_Repeat_Repost::Clear() {
// @@protoc_insertion_point(message_clear_start:LoginMessage.Name_Repeat_Repost)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.state_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Name_Repeat_Repost::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool state = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.state_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Name_Repeat_Repost::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:LoginMessage.Name_Repeat_Repost)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes name = 1;
  if (!this->_internal_name().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_name(), target);
  }

  // bool state = 2;
  if (this->_internal_state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_state(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LoginMessage.Name_Repeat_Repost)
  return target;
}

size_t Name_Repeat_Repost::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LoginMessage.Name_Repeat_Repost)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_name());
  }

  // bool state = 2;
  if (this->_internal_state() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Name_Repeat_Repost::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Name_Repeat_Repost::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Name_Repeat_Repost::GetClassData() const { return &_class_data_; }


void Name_Repeat_Repost::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Name_Repeat_Repost*>(&to_msg);
  auto& from = static_cast<const Name_Repeat_Repost&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:LoginMessage.Name_Repeat_Repost)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_state() != 0) {
    _this->_internal_set_state(from._internal_state());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Name_Repeat_Repost::CopyFrom(const Name_Repeat_Repost& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LoginMessage.Name_Repeat_Repost)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Name_Repeat_Repost::IsInitialized() const {
  return true;
}

void Name_Repeat_Repost::InternalSwap(Name_Repeat_Repost* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  swap(_impl_.state_, other->_impl_.state_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Name_Repeat_Repost::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MyEngineMessage_2eproto_getter, &descriptor_table_MyEngineMessage_2eproto_once,
      file_level_metadata_MyEngineMessage_2eproto[1]);
}

// ===================================================================

class MainMessage::_Internal {
 public:
  static const ::LoginMessage::Name_Repeat_Check& content1(const MainMessage* msg);
  static const ::LoginMessage::Name_Repeat_Repost& content2(const MainMessage* msg);
};

const ::LoginMessage::Name_Repeat_Check&
MainMessage::_Internal::content1(const MainMessage* msg) {
  return *msg->_impl_.content_.content1_;
}
const ::LoginMessage::Name_Repeat_Repost&
MainMessage::_Internal::content2(const MainMessage* msg) {
  return *msg->_impl_.content_.content2_;
}
void MainMessage::set_allocated_content1(::LoginMessage::Name_Repeat_Check* content1) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_content();
  if (content1) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(content1);
    if (message_arena != submessage_arena) {
      content1 = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, content1, submessage_arena);
    }
    set_has_content1();
    _impl_.content_.content1_ = content1;
  }
  // @@protoc_insertion_point(field_set_allocated:LoginMessage.MainMessage.content1)
}
void MainMessage::set_allocated_content2(::LoginMessage::Name_Repeat_Repost* content2) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_content();
  if (content2) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(content2);
    if (message_arena != submessage_arena) {
      content2 = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, content2, submessage_arena);
    }
    set_has_content2();
    _impl_.content_.content2_ = content2;
  }
  // @@protoc_insertion_point(field_set_allocated:LoginMessage.MainMessage.content2)
}
MainMessage::MainMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:LoginMessage.MainMessage)
}
MainMessage::MainMessage(const MainMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MainMessage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){}
    , decltype(_impl_.content_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.type_ = from._impl_.type_;
  clear_has_content();
  switch (from.content_case()) {
    case kContent1: {
      _this->_internal_mutable_content1()->::LoginMessage::Name_Repeat_Check::MergeFrom(
          from._internal_content1());
      break;
    }
    case kContent2: {
      _this->_internal_mutable_content2()->::LoginMessage::Name_Repeat_Repost::MergeFrom(
          from._internal_content2());
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:LoginMessage.MainMessage)
}

inline void MainMessage::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){0}
    , decltype(_impl_.content_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_content();
}

MainMessage::~MainMessage() {
  // @@protoc_insertion_point(destructor:LoginMessage.MainMessage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MainMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_content()) {
    clear_content();
  }
}

void MainMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MainMessage::clear_content() {
// @@protoc_insertion_point(one_of_clear_start:LoginMessage.MainMessage)
  switch (content_case()) {
    case kContent1: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.content_.content1_;
      }
      break;
    }
    case kContent2: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.content_.content2_;
      }
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = CONTENT_NOT_SET;
}


void MainMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:LoginMessage.MainMessage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.type_ = 0;
  clear_content();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MainMessage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .LoginMessage.MessageType type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::LoginMessage::MessageType>(val));
        } else
          goto handle_unusual;
        continue;
      // .LoginMessage.Name_Repeat_Check content1 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_content1(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .LoginMessage.Name_Repeat_Repost content2 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_content2(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MainMessage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:LoginMessage.MainMessage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .LoginMessage.MessageType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  // .LoginMessage.Name_Repeat_Check content1 = 2;
  if (_internal_has_content1()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::content1(this),
        _Internal::content1(this).GetCachedSize(), target, stream);
  }

  // .LoginMessage.Name_Repeat_Repost content2 = 3;
  if (_internal_has_content2()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::content2(this),
        _Internal::content2(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LoginMessage.MainMessage)
  return target;
}

size_t MainMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LoginMessage.MainMessage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .LoginMessage.MessageType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  switch (content_case()) {
    // .LoginMessage.Name_Repeat_Check content1 = 2;
    case kContent1: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.content_.content1_);
      break;
    }
    // .LoginMessage.Name_Repeat_Repost content2 = 3;
    case kContent2: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.content_.content2_);
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MainMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MainMessage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MainMessage::GetClassData() const { return &_class_data_; }


void MainMessage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MainMessage*>(&to_msg);
  auto& from = static_cast<const MainMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:LoginMessage.MainMessage)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  switch (from.content_case()) {
    case kContent1: {
      _this->_internal_mutable_content1()->::LoginMessage::Name_Repeat_Check::MergeFrom(
          from._internal_content1());
      break;
    }
    case kContent2: {
      _this->_internal_mutable_content2()->::LoginMessage::Name_Repeat_Repost::MergeFrom(
          from._internal_content2());
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MainMessage::CopyFrom(const MainMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LoginMessage.MainMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MainMessage::IsInitialized() const {
  return true;
}

void MainMessage::InternalSwap(MainMessage* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.type_, other->_impl_.type_);
  swap(_impl_.content_, other->_impl_.content_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata MainMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MyEngineMessage_2eproto_getter, &descriptor_table_MyEngineMessage_2eproto_once,
      file_level_metadata_MyEngineMessage_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace LoginMessage
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::LoginMessage::Name_Repeat_Check*
Arena::CreateMaybeMessage< ::LoginMessage::Name_Repeat_Check >(Arena* arena) {
  return Arena::CreateMessageInternal< ::LoginMessage::Name_Repeat_Check >(arena);
}
template<> PROTOBUF_NOINLINE ::LoginMessage::Name_Repeat_Repost*
Arena::CreateMaybeMessage< ::LoginMessage::Name_Repeat_Repost >(Arena* arena) {
  return Arena::CreateMessageInternal< ::LoginMessage::Name_Repeat_Repost >(arena);
}
template<> PROTOBUF_NOINLINE ::LoginMessage::MainMessage*
Arena::CreateMaybeMessage< ::LoginMessage::MainMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::LoginMessage::MainMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
